name:                chapter24
version:             0.1.0.0
github:              "JamieWohletz/chapter24"
license:             BSD3
author:              "Jamie Wohletz"
maintainer:          "reflectiveresistance@gmail.com"
copyright:           "Copyright (c) Jamie Wohletz"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/JamieWohletz/chapter24#readme>

dependencies:
- base >= 4.7 && < 5
- trifecta
- parsers
- raw-strings-qq
- containers
- text
- bytestring
- hspec
- attoparsec
- aeson
- scientific
- QuickCheck

library:
  source-dirs: src

executables:
  chapter24-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - chapter24

tests:
  chapter24-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - chapter24
