name:                chapter26
version:             0.1.0.0
github:              "JamieWohletz/chapter26"
license:             BSD3
author:              "Jamie Wohletz"
maintainer:          "reflectiveresistance@gmail.com"
copyright:           "Copyright (c) Jamie Wohletz"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/JamieWohletz/chapter26#readme>

dependencies:
- base >= 4.7 && < 5
- transformers
- scotty
- containers
- text
- wai
- random
- ansi-terminal

library:
  source-dirs: src

executables:
  chapter26-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - chapter26

tests:
  chapter26-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - chapter26
